//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinhaAgendaDeConsultas.Exceptions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceMessagesExceptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMessagesExceptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MinhaAgendaDeConsultas.Exceptions.ResourceMessagesExceptions", typeof(ResourceMessagesExceptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cpf inválido.
        /// </summary>
        public static string CPF_INVALIDO {
            get {
                return ResourceManager.GetString("CPF_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O cpf informado já está registrado na base de dados..
        /// </summary>
        public static string CPF_JA_REGISTRADO {
            get {
                return ResourceManager.GetString("CPF_JA_REGISTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O crm informado já está registrado na base de dados..
        /// </summary>
        public static string CRM_JA_REGISTRADO {
            get {
                return ResourceManager.GetString("CRM_JA_REGISTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O crm não pode estar vazio.
        /// </summary>
        public static string CRM_VAZIO {
            get {
                return ResourceManager.GetString("CRM_VAZIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data e hora de início não pode ser menor que a data e hora atual.
        /// </summary>
        public static string DATA_HORA_INICIO_MAIOR_DATA_HORA_FIM {
            get {
                return ResourceManager.GetString("DATA_HORA_INICIO_MAIOR_DATA_HORA_FIM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data e hora de fim não pode ser menor que a data e hora de início.
        /// </summary>
        public static string DATA_HORA_INICIO_MAIOR_DATA_INCLUSAO {
            get {
                return ResourceManager.GetString("DATA_HORA_INICIO_MAIOR_DATA_INCLUSAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Data ou a Hora não pode ser vazia.
        /// </summary>
        public static string DATA_HORA_VAZIO {
            get {
                return ResourceManager.GetString("DATA_HORA_VAZIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail e/ou senha inválida.
        /// </summary>
        public static string EMAIL_E_OU_SENHA_INVALIDA {
            get {
                return ResourceManager.GetString("EMAIL_E_OU_SENHA_INVALIDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email inválido.
        /// </summary>
        public static string EMAIL_INVALIDO {
            get {
                return ResourceManager.GetString("EMAIL_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O e-mail informado já está registrado na base de dados..
        /// </summary>
        public static string EMAIL_JA_REGISTRADO {
            get {
                return ResourceManager.GetString("EMAIL_JA_REGISTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O e-mail do usuario é inválido..
        /// </summary>
        public static string EMAIL_USUARIO_INVALIDO {
            get {
                return ResourceManager.GetString("EMAIL_USUARIO_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro desconhecido..
        /// </summary>
        public static string ERRO_DESCONHECIDO {
            get {
                return ResourceManager.GetString("ERRO_DESCONHECIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro inesperado..
        /// </summary>
        public static string ERRO_GENERICO {
            get {
                return ResourceManager.GetString("ERRO_GENERICO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Médico não encontrado..
        /// </summary>
        public static string MEDICO_NAO_ENCONTRADO_ESPECIALIDADE {
            get {
                return ResourceManager.GetString("MEDICO_NAO_ENCONTRADO_ESPECIALIDADE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Médico deve ser informado .
        /// </summary>
        public static string MEDICO_NAO_INFORMADO {
            get {
                return ResourceManager.GetString("MEDICO_NAO_INFORMADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome não pode estar vazio.
        /// </summary>
        public static string NOME_VAZIO {
            get {
                return ResourceManager.GetString("NOME_VAZIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Paciente deve ser informado .
        /// </summary>
        public static string PACIENTE_DEVE_SER_INFORMADO {
            get {
                return ResourceManager.GetString("PACIENTE_DEVE_SER_INFORMADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token não encotrado.
        /// </summary>
        public static string SEM_TOKEN {
            get {
                return ResourceManager.GetString("SEM_TOKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha deve ter no mínimo 6 caracteres.
        /// </summary>
        public static string SENHA_MINIMA {
            get {
                return ResourceManager.GetString("SENHA_MINIMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sessão expirada. Por favor, utilize o Refresh Token para renovar seu acesso..
        /// </summary>
        public static string TOKEN_EXPIRADO {
            get {
                return ResourceManager.GetString("TOKEN_EXPIRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O token não foi validado, faça login novamente informando a chave token..
        /// </summary>
        public static string TOKEN_NAO_VALIDADO {
            get {
                return ResourceManager.GetString("TOKEN_NAO_VALIDADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário não encontrado. Registre um usuário antes de criar um médico..
        /// </summary>
        public static string USUARIO_NAO_ENCONTRADO {
            get {
                return ResourceManager.GetString("USUARIO_NAO_ENCONTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esse e-mail ainda não foi registrado..
        /// </summary>
        public static string USUARIO_NAO_ENCONTRADO_EMAIL {
            get {
                return ResourceManager.GetString("USUARIO_NAO_ENCONTRADO_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário não está logado..
        /// </summary>
        public static string USUARIO_NAO_LOGADO {
            get {
                return ResourceManager.GetString("USUARIO_NAO_LOGADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario não tem permissão para acessar esse recurso.
        /// </summary>
        public static string USUARIO_NAO_TEM_PERMISSAO_ACESSO_RECURSO {
            get {
                return ResourceManager.GetString("USUARIO_NAO_TEM_PERMISSAO_ACESSO_RECURSO", resourceCulture);
            }
        }
    }
}
